name = "immutype_lite" 
version = "1.0.0"

description = "WORK IN PROGRESS!"

licences = ["MIT"]
repository = { type = "github", user = "yerTools", repo = "immutype_lite" } 

target = "erlang"
gleam = ">= 1.0.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
event_hub = ">= 1.0.0 and < 2.0.0"
sqlight = ">= 0.9.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
